## Упражнения по NumPy
Все задачи здесь можно (и нужно) выполнить только методами numpy без использования циклов.
Задания не обязательные и не на оценку, они нужны только для того, чтобы помочь вам получше разобраться с NumPy.

In [2]:
import numpy as np

### Линейные операторы
Даны два линейных оператора. Создайте новый оператор, который будет их композицией.

In [22]:
a = np.random.randn(8, 8)
b = np.random.randn(8, 8)
c = a.dot(b)

Примените созданный оператор из предыдущего пункта к вектору.

In [24]:
v = np.random.randn(8)
u = c.dot(v)

Посчитайте обратный оператор для оператора $c$ и примените его к вектору $u$ 

In [6]:
c_inv = np.linalg.inv(a)
u_inv = c_inv.dot(u)

### Создание и изменение массивов
Создайте верхнетреугольную матрицу со случайными элементами.

In [14]:
np.triu(np.random.randn(3,3))

array([[-0.59253033,  0.75040798, -0.06547432],
       [ 0.        , -1.1099999 ,  0.67675205],
       [ 0.        ,  0.        ,  0.32918279]])

Создайте случайную матрицу перестановки.

In [35]:
perest = np.eye(3)
np.random.shuffle(perest)
print(perest)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


Дан случайный массив. Сделайте циклический сдвиг на 2 вдоль второй оси двумя разными способами.

In [49]:
a = np.random.randn(3, 3, 3)
print(a)

[[[-0.2759176  -1.87577987 -0.37477045]
  [-0.56248815 -0.88144332  1.17793052]
  [ 0.34064115 -0.92386157  1.14506533]]

 [[ 0.40734716  0.0843021   1.43788554]
  [ 0.53366531  0.04016676  0.07755874]
  [-0.12961574 -0.75720704 -0.10822987]]

 [[-0.12824382  1.6570199   0.68256955]
  [ 0.13653083  0.20406568  0.87878175]
  [ 0.70522011  0.4708787  -1.86637305]]]


In [54]:
a1 = np.roll(a,2,axis=2)
print(a1)

[[[-1.87577987 -0.37477045 -0.2759176 ]
  [-0.88144332  1.17793052 -0.56248815]
  [-0.92386157  1.14506533  0.34064115]]

 [[ 0.0843021   1.43788554  0.40734716]
  [ 0.04016676  0.07755874  0.53366531]
  [-0.75720704 -0.10822987 -0.12961574]]

 [[ 1.6570199   0.68256955 -0.12824382]
  [ 0.20406568  0.87878175  0.13653083]
  [ 0.4708787  -1.86637305  0.70522011]]]


In [ ]:
a2 = None #?????????????????????????????????????????????????????????????????????????????????????????

Дан случайный массив. Двумя разными способами приравняйте в нем все элементы меньше 0 к 0.

In [60]:
a = np.random.randn(3, 3, 3)
print(a)

[[[-1.40907774 -0.58312624  1.33940819]
  [ 0.073377    0.570196    0.79228924]
  [ 0.09440208  0.05186753 -1.25491244]]

 [[-0.41354678  0.38862677 -0.77917598]
  [-0.53809951 -1.49336775  0.67166173]
  [-1.20936603  0.83301204  0.95812965]]

 [[-1.06295425 -0.3397564   0.88871798]
  [ 1.3064558  -0.38082499  0.24704835]
  [-0.38447496 -0.57176713 -0.14327393]]]


In [61]:
a1 = a
a1[a<0]=0
print(a1)

[[[0.         0.         1.33940819]
  [0.073377   0.570196   0.79228924]
  [0.09440208 0.05186753 0.        ]]

 [[0.         0.38862677 0.        ]
  [0.         0.         0.67166173]
  [0.         0.83301204 0.95812965]]

 [[0.         0.         0.88871798]
  [1.3064558  0.         0.24704835]
  [0.         0.         0.        ]]]


In [ ]:
a2 = None #????????????????????????????????????????????????????????????????????

Даны два набора точек в восьмимерном пространстве. Посчитайте матрицу евклидовых расстояний между всеми парами точек из первого и второго наборов.

In [158]:
a = np.random.randn(16, 8)
b = np.random.randn(32, 8)
a = [[1,2],[3,4],[5,6]]
b = [[7,8],[9,10]]
a_new = np.tile(a,(len(b),1))
b_new = np.tile(b,(1,len(a))).reshape(len(a)*len(b),len(a[0]))
# print(a_new)
# print(b_new)
s = (a_new-b_new)**2
s = np.sum(s,axis=1)
s = s**0.5
a_b_dist = s.reshape(len(b),len(a)).T
print(a_b_dist)

[[ 8.48528137 11.3137085 ]
 [ 5.65685425  8.48528137]
 [ 2.82842712  5.65685425]]


Используя посчитанную матрицу расстояний найдите для каждой точки из набора $a$ ближайшую точку из набора $b$. Вывидите индексы точек и сами точки.

In [204]:
min = np.argmin(a_b_dist,axis=1)

In [205]:
min_ind = list((zip(np.arange(0,len(min)), min)))

In [206]:
print(mins_ind)

[[0 0]
 [1 0]
 [2 0]]


In [203]:
a_b_dist[]

IndexError: list index out of range